# Generated by Django 2.1.4 on 2019-04-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Press',
            new_name='Publish',
        ),
    ]
