# Generated by Django 2.1.4 on 2019-04-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190422_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='press_id',
            new_name='publish_id',
        ),
    ]
